imports:
    - { resource: config.yml }

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: info
            handler:      grouped
        grouped:
            type: group
            members: [heroku]
        heroku: # Log les errors sur Heroku
            type:  stream
            path:  "php://stderr"
            level: error
#        database: # Log tous les messages reçus de facebook en base de donnée
#            type: stream
#            level: notice
