o_auth:
    resource: "@OAuthBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

fos_user_security:
   resource: "@FOSUserBundle/Resources/config/routing/security.xml"
   
fos_user_profile:
   resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
   prefix: /profile

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

# hwi_oauth_connect:
#     resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
#     prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect
    
facebook_login:
    path: /login/check-facebook





# fos_user_profile_edit:
#     pattern: /etudiant/modifier/profil
#     defaults: { _controller: AppBundle:Profile:edit }
#     requirements:
#         _method: GET|POST

# fos_user_show_profile:
#     pattern: /sportif/profil
#     defaults: { _controller: 'AppBundle:Profile:showProfile' }