app:
    resource: "@AppBundle/Controller/"
    type:     annotation

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

# hwi_oauth_connect:
#     resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
#     prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login
    
facebook_login:
    path: /login/check-facebook

fos_user_security:
   resource: "@FOSUserBundle/Resources/config/routing/security.xml"