# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.api_events_listener:
        class: AppBundle\Service\EventListener\ApiEventListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: 'kernel.event_listener', event: 'api.called', method: 'onApiCalled' }
    app.message_sender:
        class: AppBundle\Service\MessageSender
        arguments: [%facebook.page_access_token%, %facebook.graph_version%]
    app.football_api_service:
        class: AppBundle\Service\Football
        arguments: [%football_key%, '@event_dispatcher']
    app.basket_api_service:
        class: AppBundle\Service\Basket
        arguments: [%basket_key%, '@event_dispatcher']
    app.weather_api_service:
        class: AppBundle\Service\Weather
        arguments: [%weather_key%, "fr", "metric", '@event_dispatcher']
    app.esport_api_service:
        class: AppBundle\Service\Esport
        arguments: [%esport_csgo_key%, %esport_dota_key%, %esport_lol_key%, 'fr', '@event_dispatcher']
    app.yesorno_api_service:
        class: AppBundle\Service\YesOrNo
        arguments: ['@event_dispatcher']
    my_user_provider:
        class: AppBundle\Security\Core\User\MyOAuthProvider
        arguments: ['@fos_user.user_manager', { facebook: facebookId }, '@doctrine.orm.default_entity_manager', '@session']
    app.question_answer_service:
        class: AppBundle\Service\QuestionAnswerService
        arguments: ['@doctrine.orm.default_entity_manager']
    app.news_service:
        class: AppBundle\Service\NewsService
        arguments: [%news_key%, '@event_dispatcher']
