# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.message_sender:
        class: AppBundle\Service\MessageSender
        arguments: [%facebook.page_access_token%, %facebook.graph_version%]
    app.football_api_service:
        class: AppBundle\Service\Football
        arguments: [ doctrine.orm.entity_manager, %football_key%]
    app.football_api_service:
        class: AppBundle\Service\Basket
        arguments: [ doctrine.orm.entity_manager, %basket_key%]
